export const INIT_ROLES = 'INIT_ROLES'
export const SET_ADMIN_ROLE = 'SET_ADMIN_ROLE'
export const SET_STAFF_ROLE = 'SET_STAFF_ROLE'

export const GOOGLE_OAUTH2 = 'GOOGLE_OAUTH2'
export const LOAD_FLIGHTS = 'LOAD_FLIGHTS'
export const LOAD_BOOKINGS = 'LOAD_BOOKINGS'
export const SET_CURRENT_BOOKING = 'SET_CURRENT_BOOKING'