export const INIT_ROLES = 'INIT_ROLES'
export const SET_ADMIN_ROLE = 'SET_ADMIN_ROLE'
export const SET_STAFF_ROLE = 'SET_STAFF_ROLE'

export const GOOGLE_OAUTH2 = 'GOOGLE_OAUTH2'
export const LOAD_FLIGHTS = 'LOAD_FLIGHTS'
export const LOAD_BOOKINGS = 'LOAD_BOOKINGS'
export const CURRENT_BOOKING = 'CURRENT_BOOKING'
export const CURRENT_FLIGHT_ID = 'CURRENT_FLIGHT_ID'

export const ADMIN_LOGIN_STATUS = 'ADMIN_LOGIN_STATUS'
export const ADMIN_LOGIN_ERROR = 'LOGIN_ERROR'
export const ADMIN_LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const ADMIN_LOGOUT = 'ADMIN_LOGOUT'